### ISSUE TITLE
The interpretation of the "copy" command is incorrect.

### ISSUE THREAD

**Issue by rdebath** [vii5ard/whitespace#3]
You're pushing the wrong stack element.
The `copy` command is the analogue or the forth `pick` command, as such `1 pick` is the synonym for `over` and `0 pick` is a synonym for `dup`.

The [Sudoku solver at Whitespacers] (https://github.com/hostilefork/whitespacers/blob/master/examples/sudoku.ws) has quite a few copy commands of various depths and works correctly on the original Haskell interpreter.

NB: This also impacts your Brainfuck interpreter in WS.

**Comment by vii5ard** [comment]
Looks like the issue was fixed with c6171b180ecaf5ae8690f40b4b396f5c138ec2b7 . Please confirm by using the latest version at http://vii5ard.github.io/whitespace/ .

**Comment by rdebath** [comment]
You're quite right, I made the assumption that the two locations were identical. 
Your most recent commit should be sufficient.
